In [2]:
from sklearn import svm,datasets
iris =datasets.load_iris()

In [3]:
import pandas as pd
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df['flower']=iris.target
df['flower']=df['flower'].apply(lambda x:iris.target_names[x])
df[47:52]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
47                4.6               3.2                1.4               0.2   
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   

        flower  
47      setosa  
48      setosa  
49      setosa  
50  versicolor  
51  versicolor

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.3)

In [7]:
model = svm.SVC(kernel='rbf', C=30, gamma='auto')
model.fit(x_train, y_train)
# the score method expects x_test and y_test
model.score(x_test, y_test)

0.9555555555555556

In [8]:
from sklearn .model_selection import cross_val_score

In [12]:
cross_val_score(svm.SVC(kernel= 'linear', C=10, gamma='auto'),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [13]:
cross_val_score(svm.SVC(kernel= 'rbf', C=10, gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [14]:
cross_val_score(svm.SVC(kernel= 'rbf', C=20, gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [18]:
import numpy as np
kernels=['rbf','linear']
c=[1,10,20]
avg_scores={}
for kval in kernels:
    for cval in c:
        cv_scores=cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'),iris.data,iris.target,cv=5)
        avg_scores[kval+'_'+str(cval)]=np.average(cv_scores)
avg_scores


{'rbf_1': np.float64(0.9800000000000001),
 'rbf_10': np.float64(0.9800000000000001),
 'rbf_20': np.float64(0.9666666666666668),
 'linear_1': np.float64(0.9800000000000001),
 'linear_10': np.float64(0.9733333333333334),
 'linear_20': np.float64(0.9666666666666666)}

In [23]:
from sklearn.model_selection import GridSearchCV
clf=GridSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)
clf.fit(iris.data,iris.target)
clf.cv_results_


{'mean_fit_time': array([0.00147319, 0.00099077, 0.00104346, 0.00103827, 0.00104694,
        0.0009397 ]),
 'std_fit_time': array([3.62538479e-04, 2.33692049e-05, 2.42027623e-05, 1.33062637e-04,
        3.06689709e-05, 1.77692073e-05]),
 'mean_score_time': array([0.00116339, 0.00085464, 0.00084004, 0.0008008 , 0.00080471,
        0.00074625]),
 'std_score_time': array([5.37819737e-04, 1.39685504e-04, 2.46928915e-05, 4.11202314e-05,
        1.66472860e-05, 2.16869188e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
 

In [26]:
df=pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0       0.001473      0.000363         0.001163        0.000538        1   
1       0.000991      0.000023         0.000855        0.000140        1   
2       0.001043      0.000024         0.000840        0.000025       10   
3       0.001038      0.000133         0.000801        0.000041       10   
4       0.001047      0.000031         0.000805        0.000017       20   
5       0.000940      0.000018         0.000746        0.000022       20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [27]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667

In [28]:
clf.best_score_

np.float64(0.9800000000000001)

In [29]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [38]:
from sklearn.model_selection import RandomizedSearchCV
rs=RandomizedSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False,n_iter=2)

rs.fit(iris.data, iris.target)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       20          rbf         0.966667
1        1          rbf         0.980000

In [39]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [40]:
model_params={
    'svm':{
        'model':svm.SVC (gamma='auto'),
        'params':{
            'C':[1,10,20],
            'kernel':['rbf','linear']
        }
    },
    'random_forest':{
        'model':RandomForestClassifier(),
        'params':{
            'n_estimators':[1,5,10]
        }
    },
    'logistic_regression':{
        'model':LogisticRegression(solver='liblinear',multi_class='auto'),
        'params':{
            'C':[1,5,10]
        }
    }
}

In [42]:
score=[]
for model_name,mp in model_params.items():
  clf.fit(iris.data,iris.target)
  score.append({
      'model':model_name,
      'best_score':clf.best_score_,
      'best_params':clf.best_params_
  })

In [44]:
df=pd.DataFrame(score,columns=['model','best_score','best_params'])
df

model  best_score                best_params
0                  svm        0.98  {'C': 1, 'kernel': 'rbf'}
1        random_forest        0.98  {'C': 1, 'kernel': 'rbf'}
2  logistic_regression        0.98  {'C': 1, 'kernel': 'rbf'}